flowchart TB
    subgraph " "
    v0["Channel.fromPath"]
    v8["threads"]
    v9["telescope"]
    end
    v3([generateDMFiles])
    v5([readfile])
    v6([generateRfiFilter])
    v10([filtool])
    v12([segmented_params])
    v14([birdies])
    v15([peasoup])
    v19([parse_xml])
    v21([psrfold])
    v24([search_fold_merge])
    v25([alpha_beta_gamma_test])
    v26([pics_classifier])
    v35([create_candyjar_tarball])
    subgraph " "
    v36["-"]
    end
    v1(( ))
    v4(( ))
    v7(( ))
    v11(( ))
    v13(( ))
    v16(( ))
    v20(( ))
    v22(( ))
    v27(( ))
    v0 --> v1
    v3 --> v4
    v1 --> v5
    v5 --> v6
    v6 --> v7
    v8 --> v10
    v9 --> v10
    v7 --> v10
    v10 --> v11
    v11 --> v12
    v12 --> v13
    v13 --> v14
    v14 --> v15
    v4 --> v15
    v15 --> v16
    v16 --> v19
    v19 --> v20
    v20 --> v21
    v21 --> v22
    v22 --> v24
    v24 --> v25
    v24 --> v26
    v25 --> v27
    v26 --> v27
    v27 --> v35
    v35 --> v36
