/*
 * ============================================================================
 * Riptide FFA Pipeline - Fast Folding Algorithm Search
 * ============================================================================
 *
 * This file runs the riptide FFA search using the rffa command.
 * rffa handles everything: search, peak detection, clustering, harmonic
 * flagging, candidate filtering, and PNG plot generation.
 *
 * Input: Dedispersed time series (.inf files pointing to .dat files)
 *        Generated by PRESTO prepsubband or peasoup time series dump
 *
 * Output: CSV tables (peaks, clusters, candidates), JSON candidates, PNG plots
 *
 * Usage:
 *
 *   # Add FFA search to existing pipelines:
 *   nextflow run elden.nf -entry full --riptide.run_ffa_search true
 *   nextflow run elden.nf -entry presto_pipeline --riptide.run_ffa_search true
 *
 *   # Standalone riptide on pre-existing time series:
 *   nextflow run elden.nf -entry run_riptide_on_timeseries \
 *       --timeseries_input_dir /path/to/TIMESERIES
 *
 *   # Standalone riptide with PRESTO dedispersion:
 *   nextflow run elden.nf -entry run_riptide \
 *       --input_fil /path/to/file.fil --riptide.backend presto
 *
 * Configuration:
 *   Edit riptide_config.yml in your basedir (copied during setup_basedir)
 *
 * Documentation:
 *   https://riptide-ffa.readthedocs.io/en/latest/pipeline.html
 *
 * ============================================================================
 */

// Note: The run_riptide workflow (with PRESTO dedispersion) is defined in
// elden.nf to avoid circular imports. This file contains only the riptide
// process and simple workflows that don't require PRESTO processes.


/*
 * Riptide FFA Search
 * Runs rffa command on dedispersed time series files (.inf files)
 * rffa automatically reads .dat files referenced by the .inf files
 *
 * rffa performs:
 *   - FFA search across all DM trials
 *   - Peak detection in periodograms
 *   - Clustering of peaks across DM
 *   - Harmonic flagging and removal
 *   - Candidate filtering (DM, SNR thresholds)
 *   - PNG plot generation (if enabled in config)
 *
 * Outputs:
 *   - peaks.csv: All detected periodogram peaks
 *   - clusters.csv: Peaks grouped by frequency proximity
 *   - candidates.csv: Final candidates (harmonics removed if configured)
 *   - *.json: One JSON file per candidate (loadable with riptide.load_json)
 *   - *.png: One plot per candidate (if plot_candidates: true in config)
 */
process riptide_ffa_search {
    label 'riptide'
    label 'long'

    publishDir "${params.basedir}/${params.runID}/RIPTIDE_SEARCH", mode: 'copy'

    input:
    path inf_files
    path config_file

    output:
    path "candidates.csv", emit: candidates_csv, optional: true
    path "peaks.csv", emit: peaks_csv, optional: true
    path "clusters.csv", emit: clusters_csv, optional: true
    path "*.json", emit: candidate_json, optional: true
    path "*.png", emit: candidate_plots, optional: true

    script:
    """
    # Run riptide FFA search pipeline
    # rffa reads .inf files and automatically loads corresponding .dat files
    rffa -c ${config_file} -o . ${inf_files}
    """
}


/* ============================================================================
 * WORKFLOWS
 * ============================================================================ */


/*
 * Run Riptide FFA search on .inf files
 * Simple wrapper that runs rffa with the config file
 */
workflow riptide_search {
    take:
    inf_files_ch       // Channel of .inf files (can be collected or flat)
    config_file_ch     // Channel of riptide YAML config file

    main:
    riptide_ffa_search(inf_files_ch.collect(), config_file_ch)

    emit:
    candidates_csv = riptide_ffa_search.out.candidates_csv
    peaks_csv = riptide_ffa_search.out.peaks_csv
    clusters_csv = riptide_ffa_search.out.clusters_csv
    candidate_json = riptide_ffa_search.out.candidate_json
    candidate_plots = riptide_ffa_search.out.candidate_plots
}


/*
 * Run Riptide on pre-existing time series (.dat/.inf files)
 * Simplified entry point for when time series already exist
 */
workflow run_riptide_on_timeseries {
    main:
    if (!params.timeseries_input_dir) {
        error """
        ERROR: --timeseries_input_dir required (directory with .dat/.inf files)

        Usage:
          nextflow run elden.nf -entry run_riptide_on_timeseries \\
              --timeseries_input_dir /path/to/TIMESERIES
        """
    }

    // Get config file
    def config_path = params.riptide?.config_file ?: "${params.basedir}/riptide_config.yml"
    if (!file(config_path).exists()) {
        error "ERROR: Riptide config file not found: ${config_path}. Run setup_basedir first or specify --riptide.config_file"
    }
    config_file_ch = Channel.fromPath(config_path)

    // Get .inf files
    inf_files_ch = Channel.fromPath("${params.timeseries_input_dir}/*.inf")

    // Run riptide FFA search
    riptide_search(inf_files_ch, config_file_ch)

    emit:
    candidates_csv = riptide_search.out.candidates_csv
    candidate_plots = riptide_search.out.candidate_plots
}
